name: Publish package

on:
  push:
    tags: ["*"]

jobs:
  release:
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    permissions:
      contents: write
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_TOKEN}}
